/** 美式音标 IPA，与 dict.json 词条对应 */
module.exports = {
  a: '/ə/', an: '/ən/', the: '/ðə/', and: '/ænd/', or: '/ɔːr/', but: '/bʌt/', so: '/soʊ/',
  if: '/ɪf/', of: '/ʌv/', to: '/tuː/', in: '/ɪn/', on: '/ɑːn/', at: '/æt/', by: '/baɪ/',
  for: '/fɔːr/', from: '/frʌm/', with: '/wɪð/', without: '/wɪˈðaʊt/', into: '/ˈɪntuː/',
  upon: '/əˈpɑːn/', under: '/ˈʌndər/', over: '/ˈoʊvər/', out: '/aʊt/', up: '/ʌp/', down: '/daʊn/',
  about: '/əˈbaʊt/', there: '/ðer/', that: '/ðæt/', this: '/ðɪs/', they: '/ðeɪ/', she: '/ʃiː/',
  he: '/hiː/', her: '/hɜːr/', his: '/hɪz/', their: '/ðer/', our: '/aʊər/', my: '/maɪ/',
  your: '/jʊr/', it: '/ɪt/', we: '/wiː/', you: '/juː/', who: '/huː/', what: '/wʌt/',
  when: '/wen/', where: '/wer/', why: '/waɪ/', how: '/haʊ/', all: '/ɔːl/', each: '/iːtʃ/',
  every: '/ˈevri/', some: '/sʌm/', any: '/ˈeni/', many: '/ˈmeni/', few: '/fjuː/', one: '/wʌn/',
  two: '/tuː/', first: '/fɜːrst/', last: '/læst/', next: '/nekst/', other: '/ˈʌðər/',
  another: '/əˈnʌðər/', more: '/mɔːr/', most: '/moʊst/', very: '/ˈveri/', too: '/tuː/',
  also: '/ˈɔːlsoʊ/', just: '/dʒʌst/', only: '/ˈoʊnli/', even: '/ˈiːvən/', yet: '/jet/',
  still: '/stɪl/', already: '/ɔːlˈredi/', again: '/əˈɡen/', once: '/wʌns/', sometimes: '/ˈsʌmtaɪmz/',
  never: '/ˈnevər/', always: '/ˈɔːlweɪz/', often: '/ˈɔːfən/', soon: '/suːn/', now: '/naʊ/',
  then: '/ðen/', today: '/təˈdeɪ/', tomorrow: '/təˈmɑːroʊ/', yesterday: '/ˈjestərdeɪ/', here: '/hɪr/',
  be: '/biː/', have: '/hæv/', do: '/duː/', will: '/wɪl/', would: '/wʊd/', could: '/kʊd/',
  should: '/ʃʊd/', can: '/kæn/', may: '/meɪ/', must: '/mʌst/', might: '/maɪt/', go: '/ɡoʊ/',
  come: '/kʌm/', get: '/ɡet/', make: '/meɪk/', take: '/teɪk/', give: '/ɡɪv/', find: '/faɪnd/',
  think: '/θɪŋk/', know: '/noʊ/', see: '/siː/', look: '/lʊk/', hear: '/hɪr/', listen: '/ˈlɪsən/',
  say: '/seɪ/', tell: '/tel/', ask: '/æsk/', speak: '/spiːk/', read: '/riːd/', write: '/raɪt/',
  learn: '/lɜːrn/', study: '/ˈstʌdi/', teach: '/tiːtʃ/', work: '/wɜːrk/', try: '/traɪ/', help: '/help/',
  use: '/juːz/', need: '/niːd/', want: '/wɑːnt/', like: '/laɪk/', love: '/lʌv/', hope: '/hoʊp/',
  believe: '/bɪˈliːv/', remember: '/rɪˈmembər/', forget: '/fərˈɡet/', understand: '/ˌʌndərˈstænd/',
  decide: '/dɪˈsaɪd/', choose: '/tʃuːz/', start: '/stɑːrt/', begin: '/bɪˈɡɪn/', end: '/end/', stop: '/stɑːp/',
  stay: '/steɪ/', leave: '/liːv/', keep: '/kiːp/', change: '/tʃeɪndʒ/', grow: '/ɡroʊ/', lead: '/liːd/',
  improve: '/ɪmˈpruːv/', practice: '/ˈpræktɪs/', observe: '/əbˈzɜːrv/', notice: '/ˈnoʊtɪs/',
  pass: '/pæs/', cross: '/krɔːs/', wait: '/weɪt/', walk: '/wɔːk/', run: '/rʌn/', swim: '/swɪm/',
  meet: '/miːt/', share: '/ʃer/', laugh: '/læf/', smile: '/smaɪl/', turn: '/tɜːrn/', close: '/kloʊz/',
  open: '/ˈoʊpən/', finish: '/ˈfɪnɪʃ/', name: '/neɪm/', shine: '/ʃaɪn/', feel: '/fiːl/', call: '/kɔːl/',
  advice: '/ədˈvaɪs/', air: '/er/', aloud: '/əˈlaʊd/', april: '/ˈeɪprəl/', autumn: '/ˈɔːtəm/',
  beach: '/biːtʃ/', bench: '/bentʃ/', bicycle: '/ˈbaɪsɪkl/', big: '/bɪɡ/', blue: '/bluː/',
  boat: '/boʊt/', book: '/bʊk/', box: '/bɑːks/', bread: '/bred/', bridge: '/brɪdʒ/', bright: '/braɪt/',
  broken: '/ˈbroʊkən/', building: '/ˈbɪldɪŋ/', bus: '/bʌs/', cafe: '/kæˈfeɪ/', caf: '/kæˈfeɪ/',
  'café': '/kæˈfeɪ/', calm: '/kɑːm/', carefully: '/ˈkerfəli/', cat: '/kæt/', choice: '/tʃɔɪs/',
  city: '/ˈsɪti/', class: '/klæs/', clock: '/klɑːk/', closely: '/ˈkloʊsli/', coat: '/koʊt/',
  coffee: '/ˈkɔːfi/', coin: '/kɔɪn/', courage: '/ˈkɜːrɪdʒ/', cup: '/kʌp/', dark: '/dɑːrk/',
  dawn: '/dɔːn/', day: '/deɪ/', decision: '/dɪˈsɪʒən/', detail: '/ˈdiːteɪl/', diamond: '/ˈdaɪmənd/',
  door: '/dɔːr/', dream: '/driːm/', english: '/ˈɪŋɡlɪʃ/', evening: '/ˈiːvnɪŋ/', exam: '/ɪɡˈzæm/',
  eye: '/aɪ/', flag: '/flæɡ/', friend: '/frend/', friendship: '/ˈfrendʃɪp/', garden: '/ˈɡɑːrdn/',
  gate: '/ɡeɪt/', gift: '/ɡɪft/', habit: '/ˈhæbɪt/', hill: '/hɪl/', home: '/hoʊm/', honest: '/ˈɑːnɪst/',
  important: '/ɪmˈpɔːrtnt/', key: '/kiː/', lesson: '/ˈlesn/', letter: '/ˈletər/', library: '/ˈlaɪbreri/',
  light: '/laɪt/', lily: '/ˈlɪli/', little: '/ˈlɪtl/', long: '/lɔːŋ/', map: '/mæp/', market: '/ˈmɑːrkɪt/',
  memory: '/ˈmeməri/', mind: '/maɪnd/', mirror: '/ˈmɪrər/', mistake: '/mɪˈsteɪk/', mom: '/mɑːm/',
  monday: '/ˈmʌndeɪ/', month: '/mʌnθ/', morning: '/ˈmɔːrnɪŋ/', music: '/ˈmjuːzɪk/', neighbor: '/ˈneɪbər/',
  notebook: '/ˈnoʊtbʊk/', oak: '/oʊk/', paper: '/ˈpeɪpər/', park: '/pɑːrk/', path: '/pæθ/',
  patience: '/ˈpeɪʃns/', peaceful: '/ˈpiːsfl/', people: '/ˈpiːpl/', perfect: '/ˈpɜːrfɪkt/',
  phone: '/foʊn/', photograph: '/ˈfoʊtəɡræf/', phrase: '/freɪz/', plane: '/pleɪn/', progress: '/ˈprɑːɡres/',
  rain: '/reɪn/', recipe: '/ˈresəpi/', ring: '/rɪŋ/', river: '/ˈrɪvər/', road: '/roʊd/', room: '/ruːm/',
  secret: '/ˈsiːkrət/', seed: '/siːd/', sentence: '/ˈsentəns/', sky: '/skaɪ/', snow: '/snoʊ/',
  song: '/sɔːŋ/', star: '/stɑːr/', step: '/step/', stone: '/stoʊn/', story: '/ˈstɔːri/', street: '/striːt/',
  student: '/ˈstuːdnt/', success: '/səkˈses/', summer: '/ˈsʌmər/', sun: '/sʌn/', sunset: '/ˈsʌnset/',
  teacher: '/ˈtiːtʃər/', tea: '/tiː/', tower: '/ˈtaʊər/', town: '/taʊn/', train: '/treɪn/', tree: '/triː/',
  village: '/ˈvɪlɪdʒ/', watch: '/wɑːtʃ/', wave: '/weɪv/', week: '/wiːk/', window: '/ˈwɪndoʊ/', wind: '/wɪnd/',
  winter: '/ˈwɪntər/', wise: '/waɪz/', wood: '/wʊd/', word: '/wɜːrd/', world: '/wɜːrld/', young: '/jʌŋ/',
  time: '/taɪm/', small: '/smɔːl/', old: '/oʊld/', rose: '/roʊz/', rise: '/raɪz/', night: '/naɪt/',
  new: '/nuː/', closed: '/kloʊzd/', lost: '/lɔːst/', lose: '/luːz/', late: '/leɪt/', meeting: '/ˈmiːtɪŋ/',
  waves: '/weɪvz/', shared: '/ʃerd/', empty: '/ˈempti/', faded: '/ˈfeɪdɪd/', final: '/ˈfaɪnl/', fire: '/faɪər/',
  fresh: '/freʃ/', golden: '/ˈɡoʊldən/', green: '/ɡriːn/', hidden: '/ˈhɪdn/', locked: '/lɑːkt/',
  narrow: '/ˈnæroʊ/', painted: '/ˈpeɪntɪd/', quiet: '/ˈkwaɪət/', red: '/red/', silent: '/ˈsaɪlənt/',
  silver: '/ˈsɪlvər/', simple: '/ˈsɪmpl/', strange: '/streɪndʒ/', tall: '/tɔːl/', tiny: '/ˈtaɪni/',
  true: '/truː/', unexpected: '/ˌʌnɪkˈspektɪd/', unsent: '/ʌnˈsent/', warm: '/wɔːrm/', white: '/waɪt/',
  whole: '/hoʊl/', wooden: '/ˈwʊdn/', grandma: '/ˈɡræmɑː/', "grandma's": '/ˈɡræmɑːz/',
  asked: '/æskt/', begins: '/bɪˈɡɪnz/', believed: '/bɪˈliːvd/', changes: '/ˈtʃeɪndʒɪz/', decided: '/dɪˈsaɪdɪd/',
  felt: '/felt/', finished: '/ˈfɪnɪʃt/', gave: '/ɡeɪv/', had: '/hæd/', kept: '/kept/', knew: '/nuː/',
  laughed: '/læft/', listened: '/ˈlɪsnd/', looked: '/lʊkt/', makes: '/meɪks/', named: '/neɪmd/',
  noticed: '/ˈnoʊtɪst/', passed: '/pæst/', reading: '/ˈriːdɪŋ/', remembered: '/rɪˈmembərd/', said: '/sed/',
  shone: '/ʃoʊn/', smiled: '/smaɪld/', stopped: '/stɑːpt/', thought: '/θɔːt/', tried: '/traɪd/',
  turned: '/tɜːrnd/', wanted: '/ˈwɑːntɪd/', was: '/wʌz/', working: '/ˈwɜːrkɪŋ/', wrote: '/roʊt/',
  days: '/deɪz/', diamonds: '/ˈdaɪməndz/', eyes: '/aɪz/', friends: '/frendz/', hills: '/hɪlz/',
  leaves: '/liːvz/', letters: '/ˈletərz/', lights: '/laɪts/', memories: '/ˈmeməriz/', phrases: '/freɪzɪz/',
  planes: '/pleɪnz/', secrets: '/ˈsiːkrəts/', stars: '/stɑːrz/', steps: '/steps/', stories: '/ˈstɔːriz/',
  weeks: '/wiːks/', growing: '/ˈɡroʊɪŋ/', learning: '/ˈlɜːrnɪŋ/', crossing: '/ˈkrɔːsɪŋ/', waiting: '/ˈweɪtɪŋ/',
  herself: '/hɜːrˈself/', slowly: '/ˈsloʊli/', right: '/raɪt/', proud: '/praʊd/', tired: '/taɪərd/',
  ready: '/ˈredi/', hard: '/hɑːrd/'
};
